services:
  image-crud:
    build:
      context: image-crud
      dockerfile: docker/Dockerfile
    depends_on:
      - image-crud-postgres
      - redis
      - image-crud-s3
      - kafka-1
      - kafka-2
      - kafka-3
    secrets:
      - postgres-password
      - ssl-keystore
      - ssl-truststore
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://image-crud-postgres/image-db
      - SPRING_DATA_REDIS_HOST=redis
      - MINIO_URL=http://image-crud-s3:9000
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-1:9082,kafka-2:9083,kafka-3:9084
      - SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL=SSL
      - SPRING_KAFKA_PROPERTIES_SSL_TRUSTSTORE_LOCATION=/run/secrets/ssl-truststore
      - SPRING_KAFKA_PROPERTIES_SSL_TRUSTSTORE_PASSWORD=123456
      - SPRING_KAFKA_PROPERTIES_SSL_KEYSTORE_LOCATION=/run/secrets/ssl-keystore
      - SPRING_KAFKA_PROPERTIES_SSL_KEYSTORE_PASSWORD=123456
      - SPRING_KAFKA_PROPERTIES_SSL_KEY_PASSWORD=123456
      - SPRING_KAFKA_PROPERTIES_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
    networks:
      - image-crud-network
  image-crud-postgres:
    image: postgres
    restart: always
    secrets:
      - postgres-password
    networks:
      - image-crud-network
    environment:
      - POSTGRES_DB=image-db
      - POSTGRES_USER=judex
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
      - PG_DATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
  image-crud-s3:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: judex
      MINIO_ROOT_PASSWORD: password
    volumes:
      - minio-volume:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    networks:
      - image-crud-network
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --logLevel warning --requirePass 6k_j76,dDUl_
    volumes:
      - redis-volume:/data
    networks:
      - image-crud-network

  kafka-1:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9082:9082"
      - "29092:29092"
    secrets:
      - ssl-keystore
      - ssl-truststore
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:9092,EXTERNAL://kafka-1:9082, EXTERNAL_SAME_HOST://localhost:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_SSL_KEYSTORE_LOCATION: /run/secrets/ssl-keystore
      KAFKA_SSL_KEYSTORE_PASSWORD: 123456
      KAFKA_SSL_KEY_PASSWORD: 123456
      KAFKA_SSL_TRUSTSTORE_LOCATION: /run/secrets/ssl-truststore
      KAFKA_SSL_TRUSTSTORE_PASSWORD: 123456
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ''

      KAFKA_LISTENERS: INTERNAL://kafka-1:9092,EXTERNAL://kafka-1:9082,CONTROLLER://kafka-1:9093, EXTERNAL_SAME_HOST://:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:SSL,EXTERNAL:SSL,CONTROLLER:SSL,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:9093,2@kafka-2:9094,3@kafka-3:9095'
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_BROKER_ID: 1
      CLUSTER_ID: L0ZEQh1yTbGhNNUE7-6wSQ
#    volumes:
#      - ./image-crud/environment/kafka/server.properties:/etc/kafka/server.properties
    networks:
      - image-crud-network

  kafka-2:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9083:9083"
      - "29093:29093"
    secrets:
      - ssl-keystore
      - ssl-truststore
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:9093,EXTERNAL://kafka-2:9083, EXTERNAL_SAME_HOST://localhost:29093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_SSL_KEYSTORE_LOCATION: /run/secrets/ssl-keystore
      KAFKA_SSL_KEYSTORE_PASSWORD: 123456
      KAFKA_SSL_KEY_PASSWORD: 123456
      KAFKA_SSL_TRUSTSTORE_LOCATION: /run/secrets/ssl-truststore
      KAFKA_SSL_TRUSTSTORE_PASSWORD: 123456
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ''

      KAFKA_LISTENERS: INTERNAL://kafka-2:9093,EXTERNAL://kafka-2:9083,CONTROLLER://kafka-2:9094, EXTERNAL_SAME_HOST://:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:SSL,EXTERNAL:SSL,CONTROLLER:SSL,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:9093,2@kafka-2:9094,3@kafka-3:9095'
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_BROKER_ID: 2
      CLUSTER_ID: L0ZEQh1yTbGhNNUE7-6wSQ
#    volumes:
#      - ./image-crud/environment/kafka/server.properties:/etc/kafka/server.properties
    networks:
      - image-crud-network

  kafka-3:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9084:9084"
      - "29094:29094"
    secrets:
      - ssl-keystore
      - ssl-truststore
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-3:9094,EXTERNAL://kafka-3:9084, EXTERNAL_SAME_HOST://localhost:29094
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_SSL_KEYSTORE_LOCATION: /run/secrets/ssl-keystore
      KAFKA_SSL_KEYSTORE_PASSWORD: 123456
      KAFKA_SSL_KEY_PASSWORD: 123456
      KAFKA_SSL_TRUSTSTORE_LOCATION: /run/secrets/ssl-truststore
      KAFKA_SSL_TRUSTSTORE_PASSWORD: 123456
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ''

      KAFKA_LISTENERS: INTERNAL://kafka-3:9094,EXTERNAL://kafka-3:9084,CONTROLLER://kafka-3:9095, EXTERNAL_SAME_HOST://:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:SSL,EXTERNAL:SSL,CONTROLLER:SSL,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:9093,2@kafka-2:9094,3@kafka-3:9095'
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_BROKER_ID: 3
      CLUSTER_ID: L0ZEQh1yTbGhNNUE7-6wSQ
#    volumes:
#      - ./image-crud/environment/kafka/server.properties:/etc/kafka/server.properties
    networks:
      - image-crud-network
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 9020:8080
    secrets:
      - ssl-truststore
      - ssl-keystore
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:9082,kafka-2:9083,kafka-3:9084
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_AUDIT_TOPICAUDITENABLED: 'true'
      KAFKA_CLUSTERS_0_AUDIT_CONSOLEAUDITENABLED: 'true'
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SSL
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_LOCATION: /run/secrets/ssl-keystore
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_PASSWORD: "123456"
      KAFKA_CLUSTERS_0_SSL_TRUSTSTORELOCATION: /run/secrets/ssl-truststore
      KAFKA_CLUSTERS_0_SSL_TRUSTSTOREPASSWORD: "123456"
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ''
    networks:
      - image-crud-network

secrets:
  postgres-password:
    file: image-crud/src/main/resources/db/postgres_password.txt
  ssl-keystore:
    file: image-crud/environment/kafka/kafka.server.keystore.jks
  ssl-truststore:
    file: image-crud/environment/kafka/kafka.server.truststore.jks
networks:
  image-crud-network:
    driver: bridge

volumes:
  postgres-volume:
  redis-volume:
  minio-volume: