apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: redis-volume-reverse-colors
  name: redis-volume-reverse-colors
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
