apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: reverse-colors-processor-redis
  name: reverse-colors-processor-redis
spec:
  ports:
    - name: "6381"
      port: 6381
      targetPort: 6381
  selector:
    io.kompose.service: reverse-colors-processor-redis
