apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: tempo
  name: tempo
spec:
  ports:
    - name: "14268"
      port: 14268
      targetPort: 14268
    - name: "9411"
      port: 9411
      targetPort: 9411
    - name: "3200"
      port: 3200
      targetPort: 3200
    - name: "3201"
      port: 3201
      targetPort: 3201
  selector:
    io.kompose.service: tempo
