apiVersion: 1

datasources:
  - name: Prometheus
    label: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    uid: prometheusdatasource
  - name: tempo
    type: tempo
    uid: EbPG8fYoz
    url: http://tempo:3200
    access: proxy
    basicAuth: false
    jsonData:
      tracesToMetrics:
        datasourceUid: 'prometheusdatasource'
        spanStartTimeShift: '1h'
        spanEndTimeShift: '-1h'
        tags: [ { key: 'service.name', value: 'service' }, { key: 'job' } ]
        queries:
          - name: 'Sample query'
            query: 'sum(rate(traces_spanmetrics_latency_bucket{$$__tags}[5m]))'
      tracesToProfiles:
        datasourceUid: '-- Grafana --'
        tags: [ 'job', 'instance', 'pod', 'namespace' ]
        profileTypeId: 'process_cpu:cpu:nanoseconds:cpu:nanoseconds'
        customQuery: true
        query: 'method="${__span.tags.method}"'
      serviceMap:
        datasourceUid: 'prometheusdatasource'
      nodeGraph:
        enabled: true`
      search:
        hide: false
      traceQuery:
        timeShiftEnabled: true
        spanStartTimeShift: '1h'
        spanEndTimeShift: '-1h'
      spanBar:
        type: 'Tag'
        tag: 'http.path'