apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: image-crud-s3
  name: image-crud-s3
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: image-crud-s3
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yaml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: image-crud-s3
    spec:
      containers:
        - args:
            - server
            - /data
            - --console-address
            - :9001
          env:
            - name: MINIO_ROOT_PASSWORD
              value: password
            - name: MINIO_ROOT_USER
              value: judex
          image: minio/minio:latest
          name: image-crud-s3
          ports:
            - containerPort: 9000
              protocol: TCP
            - containerPort: 9001
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: minio-volume
      restartPolicy: Always
      volumes:
        - name: minio-volume
          persistentVolumeClaim:
            claimName: minio-volume
