spring:
  kafka:
    listener.ack-mode: manual
  profiles:
    include: dev
  config:
    import: optional:configtree:/run/secrets/
  application:
    name: image-crud
  liquibase:
    change-log: db/db-changelog.xml
  threads:
    virtual:
      enabled: true
  mvc:
    servlet:
      path: /api/v1
  datasource:
    url: jdbc:postgresql://localhost:5432/image-db
    driver-class-name: org.postgresql.Driver
    username: judex
    password: ${postgres-password:12345}
  data:
    redis:
      password: 6k_j76,dDUl_
      host: localhost
      port: 6379
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  messages:
    basename: i18n/message
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
minio:
  url: ${MINIO_URL:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:judex}
  secret-key: ${MINIO_SECRET_KEY:password}
  main-bucket: ${MINIO_MAIN_BUCKET:minio-storage}
  minor-bucket: ${MINIO_MINOR_BUCKET:minio-temp}
  image-size: ${MINIO_IMAGE_SIZE:10485760}
  ttl: ${MINIO_TTL:1}
logging:
  level:
    "liquibase": info
springdoc:
  api-docs:
    path: /swagger-ui
server:
  port: 8080
resilience4j:
  ratelimiter:
    instances:
      filter:
        limit-for-period: 1
        limit-refresh-period:
          seconds: 1s
        timeout-duration:
          seconds: 5s
management:
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
    tags:
      application: ${spring.application.name}