spring:
  kafka:
    listener.ack-mode: manual
  profiles:
    include: dev
  config:
    import: optional:configtree:/run/secrets/
  application:
    name: image-crud
  liquibase:
    change-log: db/db-changelog.xml
  threads:
    virtual:
      enabled: true
  mvc:
    servlet:
      path: /api/v1
  datasource:
    url: jdbc:postgresql://localhost:5432/image-db
    driver-class-name: org.postgresql.Driver
    username: judex
    password: ${postgres-password:12345}
  data:
    redis:
      password: 6k_j76,dDUl_
      host: localhost
      port: 6379
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  messages:
    basename: i18n/message
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
minio:
  url: http://localhost:9000
  access-key: judex
  secret-key: password
  bucket: minio-storage
  image-size: 10485760
logging:
  level:
    "liquibase": info
springdoc:
  api-docs:
    path: /swagger-ui
server:
  port: 8080