{
 "title": "Custom Dashboard",
 "description": "My attempts at creating a working custom dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Unsuccessful requests per second (5m)",
   "type": "timeseries",
   "description": "All requests which got non 200 responses per second at the run of 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{status!=\"200\"}[5m])",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Time taken to process image by filter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(instance) (imagefilter_time_seconds)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apply filter requests per second (5m)",
   "type": "timeseries",
   "description": "Requests to apply filter to image per second on the run of 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_count{uri=\"/image/{image-id}/filters/apply\"}[5m])",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Uploaded image count",
   "type": "timeseries",
   "description": "Amount of uploaded images",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "uploadimage_count_total", "legendFormat": "Uploaded images" }
   ]
  },
  {
   "title": "New registrations",
   "type": "timeseries",
   "description": "New registered users",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "registrations_count_total{exception=\"none\"}",
     "legendFormat": "Registered users"
    }
   ]
  }
 ]
}