minio:
  url: ${MINIO_URL:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:judex}
  secret-key: ${MINIO_SECRET_KEY:password}
  image-size: ${MINIO_IMAGE_SIZE:10485760}
  main-bucket: ${MINIO_MAIN_BUCKET:minio-storage}
  minor-bucket: ${MINIO_MINOR_BUCKET:minio-temp}
props:
  group: ${PROPS_GROUP:consumer-group}
  concurrency: ${PROPS_CONCURRENCY:2}
  wip-topic: ${PROPS_WIP_TOPIC:images.wip}
  done-topic: ${PROPS_DONE_TOPIC:images.done}
  type: ${PROPS_TYPE:crop}