minio:
  url: ${MINIO_URL:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:judex}
  secret-key: ${MINIO_SECRET_KEY:password}
  image-size: ${MINIO_IMAGE_SIZE:10485760}
  main-bucket: ${MINIO_MAIN_BUCKET:minio-storage}
  minor-bucket: ${MINIO_MINOR_BUCKET:minio-temp}
props:
  group: ${PROPS_GROUP:consumer-group}
  concurrency: ${PROPS_CONCURRENCY:2}
  wip-topic: ${PROPS_WIP_TOPIC:images.wip}
  done-topic: ${PROPS_DONE_TOPIC:images.done}
  type: ${PROPS_TYPE:crop}
resilience4j:
  retry:
    instances:
      imaggaRetry:
        max-attempts: 3
        wait-duration:
          seconds: 1
  circuitbreaker:
    instances:
      imaggaCB:
        register-health-indicator: true
        wait-duration-in-open-state:
          seconds: 5
        sliding-window-type: time_based
        sliding-window-size: 10
  ratelimiter:
    instances:
      imaggaRL:
        limit-for-period: 1
        limit-refresh-period:
          seconds: 1s
        timeout-duration:
          seconds: 5s
spring:
  profiles:
    include: dev
  application:
    name: image-processor
management:
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  zipkin:
    tracing:
      endpoint: http://tempo:9411/api/v2/spans