apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: kafka-1
  name: kafka-1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka-1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yaml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: kafka-1
    spec:
      containers:
        - env:
            - name: CLUSTER_ID
              value: L0ZEQh1yTbGhNNUE7-6wSQ
            - name: KAFKA_ADVERTISED_LISTENERS
              value: INTERNAL://kafka-1:9092,EXTERNAL://kafka-1:9082, EXTERNAL_SAME_HOST://localhost:29092
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: 1@kafka-1:9093,2@kafka-2:9094,3@kafka-3:9095
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: INTERNAL
            - name: KAFKA_LISTENERS
              value: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9082,CONTROLLER://0.0.0.0:9093,EXTERNAL_SAME_HOST://:29092
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: INTERNAL:SASL_SSL,EXTERNAL:SASL_SSL,CONTROLLER:SSL,EXTERNAL_SAME_HOST:PLAINTEXT
            - name: KAFKA_MIN_INSYNC_REPLICAS
              value: "1"
            - name: KAFKA_OPTS
              value: -Djava.security.auth.login.config=/run/custom-secrets/jaas
            - name: KAFKA_PROCESS_ROLES
              value: broker,controller
            - name: KAFKA_SASL_ENABLED_MECHANISMS
              value: PLAIN
            - name: KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL
              value: PLAIN
            - name: KAFKA_SSL_CLIENT_AUTH
              value: required
            - name: KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM
            - name: KAFKA_SSL_KEYSTORE_LOCATION
              value: /run/custom-secrets/ssl-keystore
            - name: KAFKA_SSL_KEYSTORE_PASSWORD
              value: "123456"
            - name: KAFKA_SSL_KEY_PASSWORD
              value: "123456"
            - name: KAFKA_SSL_TRUSTSTORE_LOCATION
              value: /run/custom-secrets/ssl-truststore
            - name: KAFKA_SSL_TRUSTSTORE_PASSWORD
              value: "123456"
          image: confluentinc/cp-kafka:latest
          name: kafka-1
          ports:
            - containerPort: 9082
              protocol: TCP
            - containerPort: 29092
              protocol: TCP
          volumeMounts:
            - mountPath: /run/custom-secrets
              name: secret-files
            - mountPath: /usr/bin/check_kafka_topics.sh
              name: kafka-1-cm0
              subPath: check_kafka_topics.sh
            - mountPath: /usr/bin/kafka_client.properties
              name: kafka-1-cm1
              subPath: kafka_client.properties
      restartPolicy: Always
      volumes:
        - name: secret-files
          projected:
            sources:
              - secret:
                  name: ssl-keystore
              - secret:
                  name: ssl-truststore
              - secret:
                  name: jaas
        - configMap:
            items:
              - key: check_kafka_topics.sh
                path: check_kafka_topics.sh
            name: kafka-1-cm0
          name: kafka-1-cm0
        - configMap:
            items:
              - key: kafka_client.properties
                path: kafka_client.properties
            name: kafka-1-cm1
          name: kafka-1-cm1
