name: Java CI with Maven
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Compile the code
        run: |
          mvn clean compile
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Verify Java checkstyle
        run: |
          mvn checkstyle:check
      - name: Verify Kotlin checkstyle
        run: |
          mvn validate
      - name: Verify Python checkstyle
        run: |
          python -m pip install --upgrade pip
#          pip install -r cv-image-processor/requirements.txt
          pip install flake8
          flake8 cv-image-processor/src --statistics --count

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Run java tests
        run: |
          mvn clean install
      - name: Jacoco Report to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: ${{ github.workspace }}/**/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 75
          min-coverage-changed-files: 75
          title: Code Coverage
          update-comment: true

      - name: Run pytest with coverage
        run: |
          python -m pop install --upgrade pip
          pip install -r cv-image-processor/requirements.txt
          pip install pytest pytest-cov
          pytest --cov=cv-image-processor/src cv-image-processor/tests --cov-report=term --cov-fail-under=75 > coverage.txt

      - name: Upload coverage report to PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ```
            ${{ steps.coverage.outputs.report }}
            ```
          token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true
  deploy:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: judexmars/image-processing-api

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: image-crud
          file: ./image-crud/docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}